### ISSUE TITLE
2nd UV channel support

### ISSUE THREAD

**Issue by Pavel3333** [SkaceKamen/wot-model-converter#9]
Unfortunately, OBJ format doesn't supports 2+ UV channels, but FBX and etc supports. Any ideas?

**Comment by atacms** [comment]
I think 2nd uv channel is not commonly used in WG models. only the uvtransform track used it to specify a AO texture. As a modder for WoT you can just ignore the 2nd channel and designate a dedicated AO via the visual file.

my fork supports DAE but doesn't bother with 2nd uv either.

**Comment by Pavel3333** [comment]
I'd worked with one of models, that placed on the Tundra map.
This model had 2nd channel that used by its shader shaders/std_effects/PBS_tiled_atlas.fx. (Model directory named as "hd_env_UNI_623_RotaryExcavator")
So after converting the model 2nd channel losts. After exporting model will be rendered incorrectly in the game.

That's why I had used SkepticalFox blender converter plugin, which can convert a model including a second UV channel

**Comment by atacms** [comment]
oh you are talking about map objects. yes almost every building uses 2nd uv, just don't consider editing them as the common use case..

anyway since you already found your alternative and I don't need that feature personally, i'll just leave it.

by the way it's not mandatory to use 2nd uv for map objects. there's a switch in visual. if you don't turn it off yet don't provided 2nd uv channel things will happen. in your case it's a excavator so it doesn't really need that stupid tiled_atlas. it's just there for the formality. or they placed tiled_atlas in the 1st channel... in that case yeah you definitely need the 2nd channel export.


normally map objects uses two channels because they want a non-repetitive texture like doors and windows overlay with a repetitve texture like brick. that's not the case for machines like rotary excavator.

**Comment by atacms** [comment]
it would seems my branch already included 2nd uv export. I forgot it even existed...

**Comment by Pavel3333** [comment]
Ok, thanks!

**Comment by SkaceKamen** [comment]
Wow, do people still use this? :O

**Comment by Pavel3333** [comment]
=) sometimes
